model:
  base_learning_rate: 1e-6
  gradient_clip_val: 1.0
  target: ldm.models.diffusion.ddpm.DDPMCustom
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    timesteps: 1000
    first_stage_key: image
    image_size: 32
    channels: 3
    monitor: train_loss
    use_ema: False
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 3
        out_channels: 3
        model_channels: 128
        attention_resolutions:
        # note: this isn/t actually the resolution but
        # the downsampling factor, i.e. this corresnponds to
        # attention on spatial resolution 8,16,32, as the
        # spatial reolution of the latents is 64 for f4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 4
        num_head_channels: 32
        use_spatial_transformer: false
        transformer_depth: 1
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 128
    num_workers: 0
    wrap: false
    train:
      target: torchvision.datasets.CIFAR10
      params:
        root: "save/CIFAR10"
        train: True
        download: True


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 2000
        max_images: 8
        increase_log_steps: False

  trainer:
    max_epochs: 20
    precision: 32