model:
  base_learning_rate: 1.0
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key:
      - "s1_mel"
      - "s2_mel"
    cond_stage_key: "mix_mel"
    image_size: 40
    image_size_h: 80
    channels: 3
    cond_stage_trainable: false
    conditioning_key: crossattn
    monitor: train_loss
    unet_config:
      target: ldm.modules.diffusionmodules.yangmodel.DiT
      params:
        input_size:
        - 40
        - 80
        patch_size:
        - 4
        - 4
        in_channels: 3
        hidden_size: 768
        depth: 12
        num_heads: 12
        custom_shape: True
    scheduler_config:
      target: ldm.lr_scheduler.LambdaWarmUpCosineScheduler
      params:
        verbosity_interval: 0
        warm_up_steps: 1000
        max_decay_steps: 50000
        lr_start: 0.0001
        lr_max: 0.0002
        lr_min: 0.00003
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 8192
        ckpt_path: "H:/exp/log/2024-03-17T19-33-51_librimix_f4/checkpoints/epoch=040-val_rec_loss=0.1223.ckpt"
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 80
          in_channels: 1
          out_ch: 1
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config: "__is_first_stage__"

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 16
    num_workers: 0
    wrap: false
    train:
      target: ldm.data.librimix.LibriMixData
      params:
        config:
          mel_path: "D:/Projects/pyprog/SepDiffReprod/data/log_mel_spec/libri2mix_train-100.csv"
          use_mel_file: True
          orig_sample_rate: 16000
          sampling_rate: 22050
          n_fft: 1024
          hop_size: 256
          win_size: 1024
          num_mels: 80
          fmin: 0
          fmax: 8000
          fixed_len: 82000
          mel_min: -11.5129
          mel_max: 1.0908

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 800
        max_images: 1
        clamp: True
        log_images_kwargs: {
             N: 1,
             n_row: 1,
        }

  trainer:
    benchmark: True
    max_epochs: 100
    precision: 16