model:
  base_learning_rate: 1.0
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key:
      - "s1_wav"
      - "s2_wav"
    cond_stage_key: "mix_wav"
    image_size: 600
    channels: 8
    cond_stage_trainable: false
    conditioning_key: crossattn
    monitor: train_loss
    e2e: true
    concat_dim: 2
    rescale_latent: False
    no_encode_source: True
    scheduler_config:
      target: ldm.lr_scheduler.LambdaWarmUpCosineScheduler
      params:
        verbosity_interval: 0
        warm_up_steps: 2000
        max_decay_steps: 50000
        lr_start: 0.00005
        lr_max: 0.0002
        lr_min: 0.00001
    unet_config:
      target: ldm.modules.diffusionmodules.yangmodel.DiTE2EV2
      params:
        input_size: 600
        in_channels: 8
        hidden_size: 384
        depth_t: 3
        depth: 12
        num_heads: 12
    first_stage_config:
      target: encodec.model.EncodecModel
      params:
        bandwidth: 6.0
    cond_stage_config: "__is_first_stage__"

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 16
    num_workers: 0
    wrap: false
    train:
      target: ldm.data.librimix.LibriMixE2E
      params:
        config:
          csv_path: "D:/Projects/pyprog/SepDiffReprod/data/encodec/libri2mix_train-100.csv"
          orig_sample_rate: 16000
          sampling_rate: 24000
          norm_min: 0
          norm_max: 1023
          fixed_len: 96000

lightning:
  callbacks:
    image_logger:
      target: main.AudioLogger
      params:
        batch_frequency: 1500
        max_audios: 1
        clamp: True
        fixed_len: 96000
        increase_log_steps: False
        orig_sr: 24000
        save_sr: 16000
        log_first_step: False
        log_audios_kwargs:
          N: 1


  trainer:
    max_epochs: 100
    precision: 32